# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven Tests PR

on:
  pull_request:
    branches: [ "main" ]


env:
  REGISTRY: ghcr.io
  JAVA_VERSION: "25"
  JAVA_DISTRIBUTION: "temurin"
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn -B test --file pom.xml
